import SwiftUI

struct MFAVerificationView: View {
    @Environment(SupabaseManager.self) private var supabaseManager
    @State private var code = ""
    @FocusState private var isInputFocused: Bool
    @State private var isLoading = false
    @State private var showError = false
    @State private var errorMessage = ""
    @State private var appearAnimation = false

    var body: some View {
        ZStack {
            AppTheme.Background.auth.ignoresSafeArea()

            VStack(spacing: 0) {
                Spacer()

                // Header icon & titles
                VStack(spacing: 20) {
                    ZStack {
                        Circle()
                            .fill(AppTheme.Brand.royalBlue.opacity(0.12))
                            .frame(width: 80, height: 80)
                        Image(systemName: "key.shield")
                            .font(.system(size: 36, weight: .medium))
                            .foregroundColor(AppTheme.Brand.royalBlue)
                    }

                    VStack(spacing: 8) {
                        Text("2-Step Verification")
                            .font(.system(size: 24, weight: .bold, design: .rounded))
                            .foregroundColor(AppTheme.Text.primary)

                        Text("Enter the 6-digit verification code generated by your Google Authenticator app.")
                            .font(.system(.subheadline, design: .rounded))
                            .foregroundColor(AppTheme.Text.secondary)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 24)
                    }
                }
                .opacity(appearAnimation ? 1 : 0)
                .offset(y: appearAnimation ? 0 : 20)
                .padding(.bottom, 36)

                // Code Input Area
                VStack(spacing: 28) {
                    ZStack {
                        // Hidden text field to capture user input
                        TextField("", text: $code)
                            .keyboardType(.numberPad)
                            .textContentType(.oneTimeCode)
                            .focused($isInputFocused)
                            .onChange(of: code) { _, newValue in
                                // Limit to 6 digits
                                if newValue.count > 6 {
                                    code = String(newValue.prefix(6))
                                }
                                
                                // Auto-submit when 6 digits are entered
                                if code.count == 6 {
                                    verifyCode()
                                }
                            }
                            // Keep it hidden but functional
                            .frame(width: 1, height: 1)
                            .opacity(0.01)

                        // Visual 6-digit input boxes
                        HStack(spacing: 12) {
                            ForEach(0..<6, id: \.self) { index in
                                let char = index < code.count ? String(code[code.index(code.startIndex, offsetBy: index)]) : ""
                                let isCurrent = index == code.count
                                
                                Text(char)
                                    .font(.system(size: 24, weight: .bold, design: .rounded))
                                    .frame(width: 48, height: 58)
                                    .background(Color.black.opacity(0.04))
                                    .clipShape(RoundedRectangle(cornerRadius: AppTheme.Radius.small, style: .continuous))
                                    .overlay(
                                        RoundedRectangle(cornerRadius: AppTheme.Radius.small, style: .continuous)
                                            .stroke(
                                                isCurrent ? AppTheme.Brand.royalBlue : Color.black.opacity(0.08),
                                                lineWidth: isCurrent ? 2 : 1
                                            )
                                    )
                                    .animation(.easeOut(duration: 0.15), value: isCurrent)
                            }
                        }
                        .onTapGesture {
                            isInputFocused = true
                        }
                    }
                    .padding(.vertical, 8)

                    // Verify button
                    Button(action: verifyCode) {
                        HStack {
                            if isLoading {
                                ProgressView()
                                    .progressViewStyle(CircularProgressViewStyle(tint: AppTheme.Text.onDark))
                                    .padding(.trailing, 8)
                            }
                            Text("Verify Code")
                                .font(.system(.title3, design: .rounded, weight: .semibold))
                        }
                        .foregroundColor(AppTheme.Text.onDark)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 18)
                        .background(AppTheme.Brand.royalBlue)
                        .clipShape(RoundedRectangle(cornerRadius: AppTheme.Radius.large, style: .continuous))
                        .shadow(
                            color: AppTheme.Brand.royalBlue.opacity(0.3),
                            radius: 10, x: 0, y: 6
                        )
                    }
                    .buttonStyle(ScaleButtonStyle())
                    .disabled(code.count < 6 || isLoading)
                    .opacity(code.count < 6 ? 0.6 : 1.0)
                    
                    // Cancel / Logout Option
                    Button(action: cancelVerification) {
                        Text("Log Out & Cancel")
                            .font(.system(size: 14, weight: .bold, design: .rounded))
                            .foregroundColor(AppTheme.Status.danger)
                            .padding(.vertical, 8)
                    }
                    .buttonStyle(PlainButtonStyle())
                }
                .padding(AppTheme.Spacing.lg + 4)
                .background(Color.white)
                .clipShape(RoundedRectangle(cornerRadius: AppTheme.Radius.form, style: .continuous))
                .overlay(
                    RoundedRectangle(cornerRadius: AppTheme.Radius.form, style: .continuous)
                        .stroke(AppTheme.Glass.border, lineWidth: 1)
                )
                .shadow(color: AppTheme.Shadow.card, radius: 24, x: 0, y: 12)
                .padding(.horizontal, AppTheme.Spacing.lg)
                .opacity(appearAnimation ? 1 : 0)
                .offset(y: appearAnimation ? 0 : 20)

                Spacer()
                Spacer()
            }
            
            // Error Alert Overlay
            if showError {
                GlassErrorAlert(
                    message: errorMessage,
                    onCancel: {
                        withAnimation(.spring(response: 0.4, dampingFraction: 0.75)) {
                            showError = false
                            code = ""
                        }
                    },
                    onTryAgain: {
                        withAnimation(.spring(response: 0.4, dampingFraction: 0.75)) {
                            showError = false
                            code = ""
                            isInputFocused = true
                        }
                    }
                )
                .zIndex(10)
            }
        }
        .onAppear {
            withAnimation(.easeOut(duration: 0.6)) {
                appearAnimation = true
            }
            // Auto focus input
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                isInputFocused = true
            }
        }
        .onTapGesture {
            isInputFocused = false
        }
    }

    private func verifyCode() {
        let impact = UIImpactFeedbackGenerator(style: .medium)
        impact.impactOccurred()
        
        isInputFocused = false
        isLoading = true
        
        Task {
            do {
                try await supabaseManager.verifyMFALogin(code: code)
                let successGenerator = UINotificationFeedbackGenerator()
                successGenerator.notificationOccurred(.success)
            } catch {
                await MainActor.run {
                    isLoading = false
                    errorMessage = error.localizedDescription
                    withAnimation(.spring(response: 0.4, dampingFraction: 0.75)) {
                        showError = true
                    }
                    let errorGenerator = UINotificationFeedbackGenerator()
                    errorGenerator.notificationOccurred(.error)
                }
            }
        }
    }

    private func cancelVerification() {
        let impact = UIImpactFeedbackGenerator(style: .light)
        impact.impactOccurred()
        
        Task {
            try? await supabaseManager.signOut()
            await MainActor.run {
                supabaseManager.mfaChallengeRequired = false
                supabaseManager.pendingFactorId = nil
            }
        }
    }
}

#Preview {
    MFAVerificationView()
        .environment(SupabaseManager.shared)
}
